# Makefile for STRAIGHT applied to Concatenative TTS
#
#	Tomoki Toda (tomoki.toda@atr.co.jp)
#			From Mar. 2001 to Sep. 2003

all:	
	@cd sp && make
	@cd sub && make
	@cd normpow && make

clean:
	@cd sp && make clean
	@cd sub && make clean
	@cd normpow && make clean
